#!/bin/sh

echo "Initial setup complete. Now doing post-up tasks."

touch "$HOME"/.psqlrc.local

# if [ -e "$HOME"/.vim/autoload/plug.vim ]; then
#   vim -E -s +PlugUpgrade +qa
# else
#   curl -fLo "$HOME"/.vim/autoload/plug.vim --create-dirs \
#       https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
# fi
# vim -u "$HOME"/.vimrc.bundles +PlugUpdate +PlugClean! +qa

if ! command -v brew &> /dev/null; then
  cat <<MSG >&2
Homebrew is not installed.
Try \`rcup' again after first installing Homebrew with

/bin/bash -c "\$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"

MSG
fi

# reset -Q

# Add mise
if ! command -v mise &> /dev/null; then
  if ! command -v brew &> /dev/null; then
    echo "Cannot install mise without brew"
  else
    echo "Installing mise"
    brew install mise
  fi
fi

# detect old OS X broken /etc/zshenv and suggest rename
if grep -qw path_helper /etc/zshenv 2>/dev/null; then
  dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd -P)

  cat <<MSG >&2
Warning: \`/etc/zshenv' configuration file on your system may cause unexpected
PATH changes on subsequent invocations of the zsh shell. The solution is to
rename the file to \`zprofile':
  sudo mv /etc/{zshenv,zprofile}

(called from ${dir}/post-up:${LINENO})

MSG
fi
